### ISSUE TITLE
Gson 解析的时候Expected a string but was BEGIN_OBJECT

### ISSUE THREAD

**Issue by gdutxiaoxu** [ikidou/TypeBuilder#1]
楼主，你好，我遇到的问题是这样的，有时间的 话麻烦解答一下

比如有这样的json字符串

```
{"showapi_res_code": 0,
  "showapi_res_error": "1",
  "showapi_res_body": {
    "totalNum": 44,
    "ret_code": 0
   }
 }
```

用下面这个解析的话是不会出错的

Bean bean = gson.fromJson(stringFromSource, 
				Bean.class);

```
public class Bean{
    int showapi_res_code;
    String showapi_res_error;
    Body showapi_res_body;
    
    public static class Body{
        int totalNum;
        int ret_code;
    }
}
```

用这一种解析的时候出错

	Bean1 bean1 = gson.fromJson(stringFromSource, Bean1.class);

```
public class Bean1 {
	int showapi_res_code;
    String showapi_res_error;
    String showapi_res_body;
    
   
}
```

错误如下

> Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 3 column 24 path $.showapi_res_body

目前fastjson 之支持这种格式的，Gson有没有办法通过自定义支持这种格式？ 谢谢

**Comment by ikidou** [comment]
从你的Json上看 showapi_res_body 字段就是一个 JsonObject，但你的Bean1 的 showapi_res_body 字段确是一个 String 类型，这在Gson里默认是否可以，下次请在博客里提吧
