### ISSUE TITLE
有啥作用呢

### ISSUE THREAD

**Issue by xinledanding** [ikidou/TypeBuilder#2]
你这个的前提是我已经知道Type是啥了 ,然后通过你的builder生成type ,感觉这样更加麻烦了啊

**Comment by ikidou** [comment]
当时是为解决我的一篇博客 [搞定Gson泛型封装](http://www.jianshu.com/p/d62c2be60617) 中所提到的那种情况：1、方便封装；2、不用自己实现Type接口；3、不用重复生成子类
