### ISSUE TITLE
小疑问

### ISSUE THREAD

**Issue by wpq2014** [ikidou/TypeBuilder#3]
我也是封装Gson看到简书文章过来的，花了好长时间才感觉基本理解了这个犀利的TypeBuilder，封装的太好了，佩服！ 有个小疑问：

return getTypeString("? extends ", upper);
        } else {
            return getTypeString("? super ", lower);
        }
    }

    private String getTypeString(String suffix, Class[] type) {
        StringBuilder sb = new StringBuilder();
        sb.append(suffix);

这个地方感觉应该用prefix

**Comment by ikidou** [comment]
哈哈，已经纠正
